### PR TITLE
Connection Pool Info Fix

### PR DESCRIPTION
**Pull request by hamzaozturk**

### CODE REVIEW

**Review by guusdk — CHANGES_REQUESTED** [review]
I do not think that this is quite right. Although the change will add a lot more useful information, it will break for any instance of Openfire where the connection provider isn't the default one.

I'm also worried about the change in the format of the file. When used, this file is probably used by automated processes. By changing the format, and adding new values (especially when doing so in the middle of the line, and not at the end of each line), we are almost certain to break every existing usage of the plugin. If we want to add more data, we should either do it at the end of the line, or in a different file, or find some other way to do this in a backwards compatible manner. In any case, it should be thoroughly documented.

**Comment by guusdk** [comment]
Hmm, no closer inspection, the documentation of this plugin describes the columns that are printed in the files to match with what this PR seems to restore.

**Comment by hamzaozturk** [comment]
Actually, i have not added any new fields.

 The current version of the code was not producing fields correctly.

```
DbConnectionManager.getConnectionProvider().toString()
```

1603815584710,org.jivesoftware.database.DefaultConnectionProvider@425d317,5,0,-1,2256957,84,70,339,0,179

Now, it produces correct output.

1603815377069,5,25,0,170250,5,0,-1,2256860,84,0,0,0,0

**Comment by akrherz** [comment]
Hi @hamzaozturk , as a part of a [git cleanup(https://github.com/igniterealtime/openfire-loadStats-plugin/pull/4), this PR will need some help.  I am attempting now to clean this up.  You did nothing wrong, this is all on my end :)

**Comment by akrherz** [comment]
Sadly, I had to redo this PR, could you please review #5 to verify your change is still accurate.  Sorry about this.

**Pull request closed without merging**
